p = input('Digite Algo: ')
print('A classe do que você digitou acima é: ', type(p))
print('Você digitou um número? ', p.isnumeric())
print('Você digitou um valor alfabético? ', p.isalpha())
print('Você digitou algo apenas em letras maiúsculas? ', p.isupper())
print('Você digitou algo apenas em letras minúsculas? ', p.islower())
print('Você digitou algo capitalizado ?', p.istitle())
print('Você digitou um valor alfanumérico? ', p.isalnum())
print('Você digitou apenas espaços? ', p.isspace())